apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helmrepositories.yaml
  - openbao.yaml
  - external-secrets.yaml
  - reloader.yaml
  - cert-manager.yaml
  - ingress-nginx.yaml
