apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- podinfo.yaml
images:
# The version pin. A "promotion" = bumping newTag here (Kargo does this later).
- name: ghcr.io/stefanprodan/podinfo
  newTag: 6.14.0
